language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
deploy:
  api_key:
    secure: ab2s5n5vhtSXpKPBogRoOpNSbBguGfkM1ALXLYoASfgikx3lyT1WIBmF3vEZu48LFUSLUy9lb5Dlv6XgMCAkCGEZj61I25CJW4TmnlFDBqo7HHe/WJv6SBZ9T7Nbvr4GR37S1lH1gxmtPk0jjpwnGU+SO1y/H+NHYez1YFSx3f5j16y0Gp+g1xM+vmVdk47Cxd1hgYzEReSL7hCplsFDP9imiOb2+WQqdZXdLCtKLcX6cULNElsFdGAJ5RApzTezFFQCgRhHiw1l/HKSuvkL9eAO+uiUKFD6GRTj/fzUbrQ4YYbnSjQYXc5Dg7xFfnQuaszmz5E47QCvIcCponC1Haaj3HYMZ+Uvqauu+YPc1AmuZAemHbZwynQhusavWLadKYfzcHid5QMKWuELAKZl3B3JV76LrXABzvm6b2Kci7v6kWbdA5+LfWf1Rl3NweqEh9rngd8OfBjNuPK+1dNAf7cE/LTmmWkFtp+CemzVSVtnk9e8xUFv5EJAgIyiJdJ34ZjSQm9jm+olFqyulazctxrpBluDXDS2tj1e5ffjBn+tVtNzv01AqPyD+RT5Z86OwQ85sTO6umCVKuR4sjDjBMukjMjsvThSiMZc7R2PrvX2Dc7r95chY7JictFWT995IMk2Yn9L/GMldAKoUo3Mi3FoJ/ijTFhjgSgXuWb2XGs=
